apiVersion: apps/v1
kind: Deployment 
metadata:
  name: auth-microservice
#  namespace: istio-system
  labels:
    app: auth-restapp
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-restapp
  template:  
    metadata:
      labels: 
        app: auth-restapp
        version: v1
    spec:
      containers:
        - name: auth
          image: papeterinnova/auth-api-dev:v1
          ports: 
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /auths/test
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /auths/test
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10