apiVersion: apps/v1
kind: Deployment 
metadata:
  name: manager-microservice
  labels:
    app: manager-restapp
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: manager-restapp
  template:  
    metadata:
      labels: 
        app: manager-restapp
        version: v1
    spec:
      containers:
        - name: manager
          image: papeterinnova/manager-api-dev:v1
          ports: 
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /managers/test
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /managers/test
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10