apiVersion: apps/v1
kind: Deployment 
metadata:
  name: session-microservice
#  namespace: istio-system
  labels:
    app: session-restapp
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: session-restapp
  template:  
    metadata:
      labels: 
        app: session-restapp
        version: v1
    spec:
      containers:
        - name: session
          image: papeterinnova/session-api-dev:v1
          ports: 
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /sessions/test
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /sessions/test
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10