apiVersion: apps/v1
kind: Deployment 
metadata:
  name: session-microservice
#  namespace: istio-system
  labels:
    app: session-restapp
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: session-restapp
  template:  
    metadata:
      labels: 
        app: session-restapp
        version: v1
    spec:
      # initContainers:
      #   - name: init-db
      #     image: busybox:1.31
      #     command: ['sh', '-c', 'echo -e "Checking for the availability of MySQL Server deployment"; while ! nc -z mysql 3306; do sleep 1; printf "-"; done; echo -e "  >> MySQL DB Server has started";']      
      containers:
        - name: session
          image: papeterinnova/session-api:v1
          # command: [ "sleep" ]
          # args: [ "infinity" ]
          ports: 
            - containerPort: 8080
          livenessProbe:
            # exec:
            #   command: 
            #     - /bin/sh
            #     - -c 
            #     - nc -z localhost 8080
            httpGet:
              path: /sessions/test
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /sessions/test
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10