apiVersion: v1
kind: Service
metadata:
  name: x-tracker-front-nodeport-service
#  namespace: istio-system
  labels:
    app: front-app
spec:
#  type: LoadBalancer
#  type: NodePort
  selector:
    app: front-app
  ports:
    - port: 4200
      name: http
      targetPort: 4200
