apiVersion: apps/v1
kind: Deployment 
metadata:
  name: x-tracker-front
  labels:
    app: front-app
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-app
  template:  
    metadata:
      labels: 
        app: front-app
        version: v1
    spec:
      # initContainers:
      #   - name: init-db
      #     image: busybox:1.31
      #     command: ['sh', '-c', 'echo -e "Checking for the availability of MySQL Server deployment"; while ! nc -z mysql 3306; do sleep 1; printf "-"; done; echo -e "  >> MySQL DB Server has started";']      
      containers:
        - name: front
          image: papeterinnova/x-tracker-front:v1
          # command: [ "sleep" ]
          # args: [ "infinity" ]
          ports: 
            - containerPort: 4200
